name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy latest changes
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -pv ~/.ssh
    - run: ssh-keyscan crazychess.xyz > ~/.ssh/known_hosts
    - run: printf -- "${{ secrets.PRIVATE_KEY }}\n" > ~/.ssh/id_ed25519
    - run: chmod 600 ~/.ssh/id_ed25519
    - run: ssh ${{ secrets.DEPLOY_USER }}@crazychess.xyz -t '. ~/.asdf/asdf.sh && ./updatethendeploy.sh'
    
